on:
  push:
    tags:
    - 'v[0-9]+\.[0-9]+\.[0-9]+-alph[0-9][0-9][0-9].*'
    
env:
  PACKAGE_SOURCE: ${{ vars.PACKAGE_SOURCE || 'nonValidPackageSource' }}
    
jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Pack
      run: |
        dotnet pack -v normal -c Release -p:PackageVersion=${VERSION} testPackagesProject.csproj --output .        
    - name: Push
      run: |
        dotnet nuget push TestNugetPackageId.TestPackagePublish.${VERSION}.nupkg --source ${PACKAGE_SOURCE} --api-key ${{ secrets.NUGET_API_KEY }}